name: pianist-transformer
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - basic-pitch
      - midi2audio
      - pretty_midi
      - mido
      - librosa
      - soundfile
      - numpy<2
      - pyyaml
      - tqdm
      - torch==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - torchaudio==2.7.1+cu118
      - beat-this==1.1.0
      - transformers==4.54.0
      - datasets==4.0.0
      - accelerate==1.10.1
      - miditoolkit==1.0.1
      - partitura==1.7.0
      - huggingface_hub==0.35.3
      - safetensors
