roles:
  - id: amoris
    name: Amoris
    ddsp_model_ckpt: third_party/ai_cover/DDSP-SVC/exp/reflow-test-amoris/model_14000.pt
    spk_id: 1
    default_pre_pitch_shift: 0

  - id: anon
    name: Anon
    ddsp_model_ckpt: third_party/ai_cover/DDSP-SVC/exp/reflow-test-anon/model_12000.pt
    spk_id: 1
    default_pre_pitch_shift: 0

  - id: doloris
    name: Doloris
    ddsp_model_ckpt: third_party/ai_cover/DDSP-SVC/exp/reflow-test-doloris/model_28000.pt
    spk_id: 1
    default_pre_pitch_shift: 0

  - id: mortis
    name: Mortis
    ddsp_model_ckpt: third_party/ai_cover/DDSP-SVC/exp/reflow-test-mortis/model_20000.pt
    spk_id: 1
    default_pre_pitch_shift: 0

  - id: soyo
    name: Soyo
    ddsp_model_ckpt: third_party/ai_cover/DDSP-SVC/exp/reflow-test-soyo/model_14000.pt
    spk_id: 1
    default_pre_pitch_shift: 0

  - id: taki
    name: Taki
    ddsp_model_ckpt: third_party/ai_cover/DDSP-SVC/exp/reflow-test-taki/model_20000.pt
    spk_id: 1
    default_pre_pitch_shift: 0

  - id: tomorin
    name: Tomorin
    ddsp_model_ckpt: third_party/ai_cover/DDSP-SVC/exp/reflow-test-tomorin/model_30000.pt
    spk_id: 1
    default_pre_pitch_shift: 0

  - id: oblivionis
    name: Oblivionis
    ddsp_model_ckpt: third_party/ai_cover/DDSP-SVC/exp/reflow-test-oblivionis/model_20000.pt
    spk_id: 1
    default_pre_pitch_shift: 0

runtime:
  upload_root: assets/uploads
  output_root: assets/output/jobs
  device: cuda
  pop2piano_model: models/pop2piano/sweetcocoa-pop2piano
  pop2piano_composer: composer1
  pop2piano_device: cuda
  pop2piano_max_length: 256
  soundfont: assets/soundfonts/extracted/usr/share/sounds/sf2/FluidR3_GM.sf2
  fluidsynth_bin: assets/soundfonts/fluidsynth_pkg/usr/bin/fluidsynth
  fluidsynth_lib_dir: assets/soundfonts/runtime_libs/usr/lib/x86_64-linux-gnu
  pitch_extractor: rmvpe
  pre_pitch_shift: 0.0
  preload_mode: torch_cuda
  require_ready_models: false
  cors_origins:
    - "*"
  constraints:
    pre_pitch_shift:
      min: -12
      max: 12
    volume:
      min: 0.0
      max: 2.0
